In [1]:
from Sudoku_Alg import solve
from Sudoku_checker import check_board
import numpy as np

In [2]:
board = [[3, 0, 6, 5, 0, 8, 4, 0, 0],
         [5, 2, 0, 0, 0, 0, 0, 0, 0],
         [0, 8, 7, 0, 0, 0, 0, 3, 1],
         [0, 0, 3, 0, 1, 0, 0, 8, 0],
         [9, 0, 0, 8, 6, 3, 0, 0, 5],
         [0, 5, 0, 0, 9, 0, 6, 0, 0],
         [1, 3, 0, 0, 0, 0, 2, 5, 0],
         [0, 0, 0, 0, 0, 0, 0, 7, 4],
         [0, 0, 5, 2, 0, 6, 3, 0, 0]]

print(np.matrix(board))

[[3 0 6 5 0 8 4 0 0]
 [5 2 0 0 0 0 0 0 0]
 [0 8 7 0 0 0 0 3 1]
 [0 0 3 0 1 0 0 8 0]
 [9 0 0 8 6 3 0 0 5]
 [0 5 0 0 9 0 6 0 0]
 [1 3 0 0 0 0 2 5 0]
 [0 0 0 0 0 0 0 7 4]
 [0 0 5 2 0 6 3 0 0]]


In [3]:
solution = solve(np.array(board))

if solution is not None:
    print(np.matrix(solution))

[[3 1 6 5 7 8 4 9 2]
 [5 2 9 1 3 4 7 6 8]
 [4 8 7 6 2 9 5 3 1]
 [2 6 3 4 1 5 9 8 7]
 [9 7 4 8 6 3 1 2 5]
 [8 5 1 7 9 2 6 4 3]
 [1 3 8 9 4 7 2 5 6]
 [6 9 2 3 5 1 8 7 4]
 [7 4 5 2 8 6 3 1 9]]


In [4]:
if check_board(solution):
    print('Solution is valid')
else:
    print('Solution is NOT valid')

Solution is valid
